// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by ignite-sr-consumer, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.azure.schemaregistry.samples
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Avro;
    using Avro.Specific;

    /// <summary>
    /// Schema for customer invoice data submitted from stores
    /// </summary>
    public partial class CustomerInvoice : ISpecificRecord
    {
        public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"CustomerInvoice\",\"namespace\":\"com.azure.schemaregistry.s" +
                "amples\",\"fields\":[{\"name\":\"InvoiceId\",\"type\":\"string\"},{\"name\":\"MerchantId\",\"typ" +
                "e\":\"string\"},{\"name\":\"TransactionValueUsd\",\"type\":\"int\"},{\"name\":\"UserId\",\"type\"" +
                ":\"string\"}]}");
        private string _InvoiceId;
        private string _MerchantId;
        private int _TransactionValueUsd;
        private string _UserId;
        public virtual Schema Schema
        {
            get
            {
                return CustomerInvoice._SCHEMA;
            }
        }
        public string InvoiceId
        {
            get
            {
                return this._InvoiceId;
            }
            set
            {
                this._InvoiceId = value;
            }
        }
        public string MerchantId
        {
            get
            {
                return this._MerchantId;
            }
            set
            {
                this._MerchantId = value;
            }
        }
        public int TransactionValueUsd
        {
            get
            {
                return this._TransactionValueUsd;
            }
            set
            {
                this._TransactionValueUsd = value;
            }
        }
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this._UserId = value;
            }
        }
        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.InvoiceId;
                case 1: return this.MerchantId;
                case 2: return this.TransactionValueUsd;
                case 3: return this.UserId;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.InvoiceId = (System.String)fieldValue; break;
                case 1: this.MerchantId = (System.String)fieldValue; break;
                case 2: this.TransactionValueUsd = (System.Int32)fieldValue; break;
                case 3: this.UserId = (System.String)fieldValue; break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
