language: java

jdk:
    - openjdk8

script:
    - ./run_tests.sh

matrix:
  include:
    - language: java
      jdk: openjdk8
      script:
      - ./run_java_tests.sh
    - language: csharp
      mono: none
      dotnet: 2.1.502
      solution: solution-name.sln
      script:
        - dotnet restore
        - dotnet test
