name: .NET Avro CITs

on:
  push:
    paths:
      - 'csharp/avro/**'
  pull_request:
    paths:
      - 'csharp/avro/**'

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: '2.1.818'
      
      - name: Restore dependencies
        run: dotnet restore csharp/avro/Microsoft.Azure.Kafka.SchemaRegistry.Avro.sln

      - name: Build
        run: dotnet build csharp/avro/Microsoft.Azure.Kafka.SchemaRegistry.Avro.sln --no-restore
      
      - name: Run tests
        run: dotnet test csharp/avro/Microsoft.Azure.Kafka.SchemaRegistry.Avro.sln --no-build --verbosity normal