name: Kafka Json CITs

on:
  push:
    paths:
      - 'java/json/**'
  pull_request:
    paths:
      - 'java/json/**'

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build package
        run: mvn -B package --file java/json/pom.xml

      - name: Run tests
        run: mvn -f java/json/pom.xml test
